module.exports = {
  instant_clone_frozen: false,
  cdroms: {},
  memory: {
    hot_add_increment_size_MiB: 0,
    size_MiB: 8192,
    hot_add_enabled: false,
    hot_add_limit_MiB: 8192,
  },
  disks: {
    2000: {
      scsi: {
        bus: 0,
        unit: 0,
      },
      backing: {
        vmdk_file:
          "[vsanDatastore] 7c08e163-1177-3fb7-f3dd-02795e6ce51e/NSX-Edge-1.vmdk",
        type: "VMDK_FILE",
      },
      label: "Hard disk 1",
      type: "SCSI",
      capacity: 210453397504,
    },
  },
  parallel_ports: {},
  sata_adapters: {},
  cpu: {
    hot_remove_enabled: false,
    count: 4,
    hot_add_enabled: false,
    cores_per_socket: 1,
  },
  scsi_adapters: {
    1000: {
      scsi: {
        bus: 0,
        unit: 7,
      },
      label: "SCSI controller 0",
      sharing: "NONE",
      type: "LSILOGIC",
    },
  },
  power_state: "POWERED_ON",
  floppies: {},
  identity: {
    name: "NSX-Edge-1",
    instance_uuid: "5015b058-1bf9-e453-ff87-47a516495738",
    bios_uuid: "4215ac7e-6555-abeb-b315-51a20af12b2d",
  },
  nvme_adapters: {},
  name: "NSX-Edge-1",
  nics: {
    4000: {
      start_connected: true,
      upt_v2_compatibility_enabled: false,
      backing: {
        connection_cookie: 1675692343,
        distributed_port: "d4e71279-cfd1-46a6-a901-f3f2fa574e69",
        distributed_switch_uuid:
          "89 a9 16 ae a6 23 11 ed-b5 02 6b ef 1d 46 08 6f",
        type: "DISTRIBUTED_PORTGROUP",
        network: "dvportgroup-26",
      },
      mac_address: "00:50:56:95:dd:4d",
      mac_type: "ASSIGNED",
      allow_guest_control: false,
      wake_on_lan_enabled: true,
      label: "Network adapter 1",
      state: "CONNECTED",
      type: "VMXNET3",
      upt_compatibility_enabled: true,
    },
    4001: {
      start_connected: true,
      upt_v2_compatibility_enabled: false,
      backing: {
        connection_cookie: 1675692343,
        distributed_port: "fbe12fd6-6232-4a49-b8d8-1aa66574009c",
        distributed_switch_uuid:
          "89 a9 16 ae a6 23 11 ed-b5 02 6b ef 1d 46 08 6f",
        type: "DISTRIBUTED_PORTGROUP",
        network: "dvportgroup-32",
      },
      mac_address: "00:50:56:95:37:f9",
      mac_type: "ASSIGNED",
      allow_guest_control: false,
      wake_on_lan_enabled: true,
      label: "Network adapter 2",
      state: "CONNECTED",
      type: "VMXNET3",
      upt_compatibility_enabled: true,
    },
    4002: {
      start_connected: false,
      upt_v2_compatibility_enabled: false,
      backing: {
        network_name: "none",
        type: "STANDARD_PORTGROUP",
        network: "network-45",
      },
      mac_address: "00:50:56:95:0f:30",
      mac_type: "ASSIGNED",
      allow_guest_control: false,
      wake_on_lan_enabled: true,
      label: "Network adapter 3",
      state: "NOT_CONNECTED",
      type: "VMXNET3",
      upt_compatibility_enabled: true,
    },
    4003: {
      start_connected: false,
      upt_v2_compatibility_enabled: false,
      backing: {
        network_name: "none",
        type: "STANDARD_PORTGROUP",
        network: "network-45",
      },
      mac_address: "00:50:56:95:1f:9d",
      mac_type: "ASSIGNED",
      allow_guest_control: false,
      wake_on_lan_enabled: true,
      label: "Network adapter 4",
      state: "NOT_CONNECTED",
      type: "VMXNET3",
      upt_compatibility_enabled: true,
    },
    4004: {
      start_connected: false,
      upt_v2_compatibility_enabled: false,
      backing: {
        network_name: "none",
        type: "STANDARD_PORTGROUP",
        network: "network-45",
      },
      mac_address: "00:50:56:95:fd:84",
      mac_type: "ASSIGNED",
      allow_guest_control: false,
      wake_on_lan_enabled: true,
      label: "Network adapter 5",
      state: "NOT_CONNECTED",
      type: "VMXNET3",
      upt_compatibility_enabled: true,
    },
  },
  boot: {
    delay: 0,
    retry_delay: 10000,
    enter_setup_mode: false,
    type: "BIOS",
    retry: false,
  },
  serial_ports: {},
  boot_devices: [],
  guest_OS: "UBUNTU_64",
  hardware: {
    upgrade_policy: "NEVER",
    upgrade_status: "NONE",
    version: "VMX_19",
  },
};
